services:
 
    kitodo-app:
        extends:
            file: kitodo-services.yml
            service: kitodo-app
        
        depends_on:
            - kitodo-db
            - kitodo-es
            - kitodo-mq
            
        volumes:
            - ${APP_DATA}:/usr/local/kitodo
            - ${APP_CONFIG}:/usr/local/tomcat/webapps/kitodo/WEB-INF/classes
            - type: bind
              source: ${APP_OVERWRITES_DATA}
              target: /tmp/kitodo/overwrites/data
            - type: bind
              source: ./overwrites/app/sql/kitodo_post_init.sql
              target: /tmp/kitodo/overwrites/sql/post_init.sql  
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
    
    
    kitodo-db:
        extends:
            file: kitodo-services.yml
            service: kitodo-db
    
    
    kitodo-es:
        extends:
            file: kitodo-services.yml
            service: kitodo-es
    
    
    kitodo-mq:
        extends:
            file: kitodo-services.yml
            service: kitodo-mq
