services:
 
    kitodo-app:
        
        build:
            args:
                BUILDER_TYPE: git
                BUILDER_GIT_COMMIT: ${APP_BUILDER_GIT_COMMIT}
                BUILDER_GIT_SOURCE_URL: ${APP_BUILDER_GIT_SOURCE_URL}
